name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for your effort to make me busy, I appreciate this a lot (for real)"
        pr-message: "Thanks for your contribution to this crap. Your works will (may)be review and appreciated."
